[package]
name = "rust-video-player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gstreamer = "0.16.0"
gstreamer-app = "0.16.0"
gstreamer-video = "0.16.0"